### ISSUE TITLE
Error when trying to run tests

### ISSUE THREAD

**Issue by Mikerah** [libp2p/interop#11]
When I try to run the tests (both the dht tests and my own tests), I get the following error:

`Error: the string "flag provided but not defined: -ls\nUsage of /home/mikerah/Documents/Projects/interop/node_modules/go-libp2p-dep/go-libp2p/p2pd:\n" was thrown, throw an Error :)`

The error gets thrown when I try to spawn 2 go daemons:
`daemons = await spawnDaemons(2, 'go')`.

System Info:
OS: Fedora 27
OS type: 64-bit
Processor: Intel Core i7

**Comment by vasco-santos** [comment]
Hello @Mikerah 

Thanks for reaching out with this. Are the other tests working properly?

**Comment by vasco-santos** [comment]
Closing for lack of updates
