### ISSUE TITLE
unskip dht content fetching tests

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/interop#15]
In the context of [libp2p/interop#7](https://github.com/libp2p/interop/pull/7), the `content-fetching` tests are disabled because we need to be able to customize the validator and selector functions. 

This needs the following issues to be solved first, both in `go-libp2p-daemon` and `js-libp2p-daemon`:

- [ ] [libp2p/go-libp2p-daemon#81](https://github.com/libp2p/go-libp2p-daemon/issues/81)
- [ ] [libp2p/go-libp2p-daemon#63](https://github.com/libp2p/go-libp2p-daemon/issues/63)

**Comment by achingbrain** [comment]
Content fetching tests are no longer skipped
