### ISSUE TITLE
Add interop tests for different key types

### ISSUE THREAD

**Issue by jacobheun** [libp2p/interop#20]
After some discussion on the [libp2p discuss forums](https://discuss.libp2p.io/t/browser-go-bootstrap-and-connect/175), it would be ideal to have interop tests to verify different peer key types are working properly across implementations. The current interop tests are only validating RSA keys.

**Comment by aknuds1** [comment]
I would like to try to solve this, as it's of relevance to our project (Quorum Control).

**Comment by aknuds1** [comment]
@jacobheun Could you give me a hint as to where the peer key type is configured in test/connect/js2go.js? I'm not familiar enough with libp2p internals to tell yet; I scoured through the tests and the immediate API and couldn't figure out so far, I suppose RSA use is implicit?

**Comment by jacobheun** [comment]
@aknuds1 `spawnDaemons` takes an optional 3rd argument of options. These are the libp2p-daemon flags, and would be something like: `daemons = await spawnDaemons(2, ['js', 'go'], { id: '/path/to/key' })`. The tests use the https://github.com/libp2p/go-libp2p-daemon and https://github.com/libp2p/js-libp2p-daemon libraries. Support for key file reading should already exist, the key files will just need to be generated.

These tests should end up failing. JS currently has some open issues we need to get resolved for supporting the other keys, namely:
- [ ] https://github.com/libp2p/js-libp2p-crypto/issues/129, generating keys, this can cause issues storing keys on the libp2p keychain
- [ ] https://github.com/libp2p/js-libp2p-crypto/issues/145, importing keys, this will be a blocker for importing. Right now I believe the import will assume rsa.

**Comment by aknuds1** [comment]
Thanks @jacobheun! I also came to the conclusion I had to provide a key through the `-id` parameter to the daemon. I'm in the process of producing an ECDSA private key file.

**Comment by aknuds1** [comment]
@jacobheun I'm able to break the tests now, by using ECDSA keys.

**Comment by jacobheun** [comment]
@aknuds1 that's great! Ideally what I think interop should be doing is running through all the tests with different keys, but that's a scenario I think we can add later. The advantage of doing that is making sure things like pubsub signature verification is working correctly with various keys types.

I think we could look at pushing up these failing tests and allow them to fail in CI so we at least have visibility while we work on finishing support in JS.

**Comment by aknuds1** [comment]
@jacobheun I'll make a PR then, so you can provide feedback.

**Comment by aknuds1** [comment]
@jacobheun Please have a look at my PR #21. I'm open to feedback on this as a starting point.

**Comment by vasco-santos** [comment]
This seems done! :D
